-- MySQL Script generated by MySQL Workbench
-- Fri Aug 28 21:27:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema artful_menu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artful_menu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artful_menu` DEFAULT CHARACTER SET utf8 ;
USE `artful_menu` ;

-- -----------------------------------------------------
-- Table `artful_menu`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artful_menu`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `seats` INT NOT NULL,
  `img_path` VARCHAR(512) NULL,
  `open` TIME NOT NULL,
  `close` TIME NOT NULL,
  `last_order` TIME NOT NULL,
  `exception` VARCHAR(200) NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artful_menu`.`rule_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artful_menu`.`rule_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artful_menu`.`rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artful_menu`.`rule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NULL,
  `store_id` INT NOT NULL,
  `rule_category_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rule_store_idx` (`store_id` ASC) ,
  INDEX `fk_rule_rule_category1_idx` (`rule_category_id` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_rule_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `artful_menu`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rule_rule_category1`
    FOREIGN KEY (`rule_category_id`)
    REFERENCES `artful_menu`.`rule_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artful_menu`.`menu_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artful_menu`.`menu_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artful_menu`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artful_menu`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `img_path` VARCHAR(512) NULL,
  `enabled` TINYINT(1) NOT NULL,
  `store_id` INT NOT NULL,
  `menu_category_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_store1_idx` (`store_id` ASC) ,
  INDEX `fk_menu_menu_category1_idx` (`menu_category_id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_menu_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `artful_menu`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_menu_category1`
    FOREIGN KEY (`menu_category_id`)
    REFERENCES `artful_menu`.`menu_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artful_menu`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artful_menu`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` INT NOT NULL,
  `store_id` INT NOT NULL,
  `enter_datetime` DATETIME NOT NULL,
  `leave_datetime` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guest_store1_idx` (`store_id` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_guest_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `artful_menu`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
